# Generated by Django 3.1 on 2020-08-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitordetection',
            table='visitor_detection',
        ),
    ]
